- name: Prep builder
  hosts: all
  gather_facts: true # Required to add user to libvirt group

  roles:
    - role: prep_builder
      become: true

  post_tasks:
    - name: Run Packer init
      command: 
        cmd: packer init prod.pkr.hcl
        chdir: "{{ playbook_dir }}/packfiles"
      tags: packer