- name: Prep builder
  hosts: localhost
  gather_facts: true # Required to add user to libvirt group

  roles:
    - role: prep_builder
      become: true

  post_tasks:
    - name: Run Packer init
      command:
        cmd: packer init prod.pkr.hcl
        chdir: "{{ playbook_dir }}/packfiles"
      tags: packer

- name: Build images
  hosts: localhost
  gather_facts: false

  roles:
    - role: run_packer
      build_variant: "ubuntu2204"
  tags:
    - all
    - ubuntu
    - ubuntu2204
