---
- name: Prepare STFC Cloud user image with our security compliance baseline
  hosts: all
  pre_tasks:
    - name: User warning
      ansible.builtin.debug:
        msg: "[Warning] Do not run on non-cloud machine"

  roles:
    - role: vm_baseline
    - role: container_registry
    - role: nubes_bootcontext
    - role: admin_keys
    - role: wazuh
    - role: rsyslog
    - role: pakiti
