---
- name: Prepare the image with the STFC security baseline
  hosts: all
  pre_tasks:
    - name: User warning
      ansible.builtin.debug:
        msg: "[Warning] Do not run on non-cloud machine"

  roles:
    - role: vm_baseline
    - role: container_registry
    - role: nubes_bootcontext
    - role: tidy_image