- name: Create working directory in tmp
  file:
    path: "{{ packer_dir }}"
    state: directory
    mode: 0755

- name: Copy required files to host
  synchronize:
    src: "{{ playbook_dir }}/"
    dest: "{{ packer_dir }}"
    delete: true
    recursive: true
    mode: push

- name: Install packer plugins
  shell:
    chdir: "{{ packer_dir }}/packfiles"
    cmd: packer init plugins.pkr.hcl
