- name: Ensure yum.quattor.repos.d directory exists
  ansible.builtin.file:
    # If we place these repos in /etc/yum.repos.d quattor will not update
    # them and creating duplicate packages across the system and quattor repo dirs
    # conflicts. Instead get them into the right place so quattor's spma
    # takes over and puts the right conf in on first-boot
    path: "{{ quattor_repo_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Remove the built-in epel repository to switch to the gridpp mirror 
  ansible.builtin.dnf:
    name: epel-release
    state: absent
  become: true

- name: Add gridpp mirror EPEL repository
  ansible.builtin.yum_repository:
    name: epel-{{ ansible_facts.distribution_major_version }}-x86_64
    description: "EPEL {{ ansible_facts.distribution_major_version }} Repository"
    baseurl: "http://mirrors.gridpp.rl.ac.uk/current/epel-{{ ansible_facts.distribution_major_version }}-x86_64/RPMS.base/"
    enabled: true
    gpgcheck: false
    state: present
    reposdir: "{{ quattor_repo_dir }}"
  become: true

- name: Add Powertools repository
  ansible.builtin.yum_repository:
    name: rocky-{{ ansible_facts.distribution_major_version }}x-x86_64-powertools
    description: Rocky Mirror powertools
    baseurl: "http://mirrors.gridpp.rl.ac.uk/current/rocky-{{ ansible_facts.distribution_major_version }}-x86_64/RPMS.powertools/"
    enabled: true
    gpgcheck: true
    state: present
    module_hotfixes: true
    reposdir: "{{ quattor_repo_dir }}"
  become: true

- name: Add Rocky mirror repositories crb
  ansible.builtin.yum_repository:
    name: rocky-{{ ansible_facts.distribution_major_version }}x-x86_64-crb
    description: Rocky Mirror crb
    baseurl: "http://mirrors.gridpp.rl.ac.uk/current/rocky-{{ ansible_facts.distribution_major_version }}-x86_64/RPMS.crb/"
    enabled: true
    gpgcheck: true
    state: present
    module_hotfixes: true
    reposdir: "{{ quattor_repo_dir }}"
  become: true
  when: ansible_facts.distribution_major_version == '9'

- name: Add Rocky mirror repositories
  ansible.builtin.yum_repository:
    name: rocky-{{ ansible_facts.distribution_major_version }}x-x86_64-{{ item }}
    description: Rocky Mirror {{ item }}
    baseurl: "http://mirrors.gridpp.rl.ac.uk/current/rocky-{{ ansible_facts.distribution_major_version }}-x86_64/RPMS.{{ item }}/"
    enabled: true
    gpgcheck: true
    state: present
    module_hotfixes: true
    reposdir: "{{ quattor_repo_dir }}"
  with_items:
    - extras
    - os
  become: true

- name: Add Quattor repositories
  ansible.builtin.yum_repository:
    name: "{{ item }}"
    description: "{{ item }} Repository"
    baseurl: "http://mirrors.gridpp.rl.ac.uk/live/quattor-noarch/RPMS.{{ item }}/"
    enabled: true
    gpgcheck: false
    state: present
    reposdir: "{{ quattor_repo_dir }}"
  become: true
  loop:
    - externals-el{{ ansible_facts.distribution_major_version }}
    - quattor-{{ quattor_version }}-el{{ ansible_facts.distribution_major_version }}

- name: Ensure dnf uses the quattor repos and the default ones to bootstrap quattor packages
  ansible.builtin.lineinfile:
    regexp: '^reposdir='
    line: "reposdir=/etc/yum.repos.d,{{ quattor_repo_dir }}"
    insertafter: '\[main\]'
    path: "{{ item }}"
  with_items:
    - /etc/dnf/dnf.conf
    - /etc/yum.conf
  become: true

- name: Install packages
  ansible.builtin.dnf:
    name:
      - ncm-ncd
      - ncm-spma
      - ncm-cdispd
  become: true

- name: Create cloud-init config to run the script
  ansible.builtin.copy:
    src: 99-set-aquilon-profile.cfg
    dest: /etc/cloud/cloud.cfg.d/
    owner: root
    group: root
    mode: "0644"
  become: true
