- name: Check only root, rocky, ubuntu and cloud users exist
  ansible.builtin.command: awk -F':' '($3 == 0 || $3 >= 1000) && $3 < 65534 && $1 !~ /^(root|rocky|ubuntu|cloud)$/ {print $1}' /etc/passwd
  register: run_test_unexpected_users
  changed_when: false
  failed_when: run_test_unexpected_users.stdout != ""

- name: Check hostname is contains the IP address of the host in the format host-<IP_ADDRESS>.nubes.stfc.ac.uk
  ansible.builtin.command: hostname
  register: run_test_hostname
  changed_when: false
  failed_when: run_test_hostname.stdout is not match('^host-' + ansible_facts['default_ipv4']['address'].replace('.', '-') + '\.nubes\.stfc\.ac\.uk$')
  # We cannot set the hostname on a GitHub actions container, so we skip this check if we are in a container
  when: not in_container
