- name: Print build variant
  debug:
    msg: "Building: {{ build_variant }}"

- name: Print packer command for debugging
  debug:
    msg: "Running: cd {{ packer_dir }}/packfiles && packer build {{ build_variant }}.pkr.hcl"

- name: Start packer build
  shell:
    chdir: "{{ packer_dir }}/packfiles"
    cmd: packer build {{ build_variant }}.pkr.hcl
