#!/bin/bash

set -euo pipefail

sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install gpg-agent ansible locales -y
sudo apt-get clean all
/usr/bin/gpg-agent --daemon

/usr/bin/git clone https://github.com/stfc/cloud-image-builders.git --depth=1

sudo locale-gen en_US.UTF-8

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

cd cloud-image-builders

hostname
sed -i "s/hosts: default/hosts: localhost/g" os_builders/*.yml
mkdir -p /var/ossec/etc/extra
echo "{\"groups\": [\"default\", \"cloud\", \"ubuntu\", \"debian\", \"octavia-amphora\"], \"labels\": {\"amphora-build-date\": \"$(date '+%Y-%m-%d %H:%M:%S')\" }}" > /var/ossec/etc/extra/03-amphora.json
ansible-playbook os_builders/configure_os_images.yml -i .github/localhost.yml
echo "130.246.210.20 wazuh.cape.stfc.ac.uk" >> /etc/hosts

apt-get autoremove -y
