- name: Add wazuh repo
  ansible.builtin.yum_repository:
    name: wazuh
    file: wazuh
    description: "Repository to install wazuh"
    baseurl: https://packages.wazuh.com/4.x/yum/
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
  become: true

- name: Install wazuh
  ansible.builtin.dnf:
    name:
      - wazuh-agent-4.14.*
    state: present
  become: true
