- name: Get cloud group info
  ansible.builtin.getent:
    database: group
    split: ":"
    key: cloud

- name: Remove users in cloud group
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: true
  loop: "{{ ansible_facts.getent_group.cloud[2] | split(',') }}"
  become: true

- name: Mark next boot as first boot
  file:
    path: /var/lock/firstboot
    state: touch
  become: true
