- name: Cleanup old kernels Ubuntu
  block:
  - name: cleanup old kernels
    shell: "dpkg --list | egrep -i 'linux-image|linux-headers|linux-modules' | cut -d ' ' -f 3 | grep -v $(uname -r) | grep -v 'linux-headers-generic' | grep -v 'linux-headers-virtual' | grep -v 'linux-image-virtual' | xargs apt-get remove -y"
    become: true
    when: ( ansible_facts.packages['linux-image'] | length > 1)
  when: ansible_distribution == "Ubuntu" and "linux-image" in ansible_facts.packages

- name: Cleanup old kernels Rocky
  block:
  - name: cleanup old kernels
    command:
      cmd: "dnf remove --oldinstallonly kernel -y"
    when: ( ansible_facts.packages['kernel'] | length > 1)
  when: ansible_distribution == "Rocky" and "kernel" in ansible_facts.packages
