- name: Remove duplicate /etc/logrotate.d/btmp
  ansible.builtin.file:
    path: "/etc/logrotate.d/btmp"
    state: absent
  when: ansible_distribution == "Rocky"
  become: true

- name: Remove duplicate /etc/logrotate.d/wtmp
  ansible.builtin.file:
    path: "/etc/logrotate.d/wtmp"
    state: absent
  when: ansible_distribution == "Rocky"
  become: true

- name: Clear Audit log
  ansible.builtin.shell: "logrotate -f /etc/logrotate.conf"
  become: true

- name: Cleanout /var/log/*.gz
  ansible.builtin.file:
    path: "/var/log/*.gz"
    state: absent
  become: true
