- name: Set wazuh package name variable
  ansible.builtin.set_fact:
    wazuh_package_name: "wazuh-agent"

- name: Stop wazuh-agent service
  ansible.builtin.command:
    cmd: "systemctl stop wazuh-agent.service"
  ignore_errors: True
  become: true
  when: wazuh_package_name in ansible_facts.packages or in_container

- name: Clean Wazuh agent history
  ansible.builtin.file:
    path: "/var/ossec/etc/client.keys"
    state: absent
  become: true
