- name: Stop wazuh-agent service
  ansible.builtin.systemd:
    name: wazuh-agent
    state: stopped
  when: not in_container
  become: true

- name: Clean Wazuh agent history
  ansible.builtin.file:
    path: "/var/ossec/etc/client.keys"
    state: absent
  become: true
