- name: Create containerd directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - /etc/containerd/conf.d/
    - /etc/containerd/certs.d/docker.io/

- name: Copy config for docker.io mirror
  copy:
    src: dockerhub-hosts.toml
    dest: /etc/containerd/certs.d/docker.io/hosts.toml
    mode: 0644

- name: Copy config to point CRI to /etc/containerd/certs.d
  copy:
    src: cri-registry.toml
    dest: /etc/containerd/conf.d/cri-registry.toml
    mode: 0644

- name: Create a file to hold the Nvidia container config
  file:
    path: /etc/containerd/conf.d/nvidia.toml
    state: touch
