---
- name: Install EPEL repository
  ansible.builtin.package:
    name: epel-release
    state: latest
  become: true
  when: ansible_facts['distribution'] == "Rocky"

- name: Install bash-completion package
  ansible.builtin.package:
    name: bash-completion
    state: latest
  become: true
  when: ansible_facts['distribution'] == "Rocky"
