- name: Copy Pakiti RPM
  copy:
    src: "files/pakiti-client-2.1.4-3.RAL.noarch.rpm"
    dest: "/tmp/pakiti-client-2.1.4-3.RAL.noarch.rpm"

- name: Gather Package facts
  package_facts:
    manager: auto

- name: Install Pakiti on Ubuntu using Alien
  block:
    - name: Enable Universe for Alien
      apt_repository:
        repo: "{{ item }}"
      loop:
        - "deb http://archive.ubuntu.com/ubuntu/ {{ansible_distribution_release}} main"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ansible_distribution_release}} universe"

    - name: Install Alien for Pakiti
      apt:
        name: alien
        state: present
        update_cache: yes

    - name: Install Pakiti using Alien
      command:
        cmd: "alien --install /tmp/pakiti-client-2.1.4-3.RAL.noarch.rpm"

    - name: Remove Alien
      apt:
        name: alien
        state: absent

    - name: Remove universe repository
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu/ {{ansible_distribution_release}} universe"
        state: absent

    - name: Update apt-cache
      apt:
        update_cache: yes
  when: ansible_distribution == "Ubuntu" and 'pakiti-client' not in ansible_facts.packages

- name: Install Pakiti on RL
  yum:
    name: "/tmp/pakiti-client-2.1.4-3.RAL.noarch.rpm"
    state: present
    disable_gpg_check: true
  when: ansible_distribution == "Rocky"
