- name: Make sure perl is installed
  become: true
  ansible.builtin.package:
    name: perl
    state: latest

- name: Copy Pakiti client script
  become: true
  ansible.builtin.copy:
    src: pakiti3
    dest: /usr/sbin/pakiti3
    mode: '0554'
    owner: 'root'
    group: 'root'

- name: Create a cron entry to run the client
  become: true
  ansible.builtin.cron:
    name: Report to Pakiti Server
    minute: 17
    hour: 7
    job: '/usr/sbin/pakiti3 --url "https://pakiti.stfc.ac.uk/feed/" --site Cloud'
