- name: Make sure perl is installed
  become: true
  ansible.builtin.package:
    name: perl
    state: latest

- name: Copy Pakiti client script
  become: true
  ansible.builtin.copy:
    src: pakiti3
    dest: /usr/sbin/pakiti3
    mode: '0554'
    owner: 'root'
    group: 'root'

- name: Copy the run script to cron.daily
  become: true
  ansible.builtin.copy:
    src: run-pakiti
    dest: /etc/cron.daily/run-pakiti
    mode: '0554'
    owner: 'root'
    group: 'root'
