- name: Error for unknown distributions
  ansible.builtin.fail:
    msg: "Unknown distribution {{ ansible_distribution }}"
  when: ansible_distribution != "Rocky" and ansible_distribution != "Ubuntu"

- name: Install system updates for RL systems
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  when: ansible_distribution == "Rocky"
  register: result
  until: result is not failed
  retries: 5
  delay: 30
  become: true

- name: Install system updates for Ubuntu systems
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    autoremove: true
    autoclean: true
  when: ansible_distribution == 'Ubuntu'
  register: result
  until: result is not failed
  retries: 5
  delay: 30
  become: true

- name: get IP
  ansible.builtin.shell: hostname -I
  register: my_hostname

- name: print IP
  ansible.builtin.debug:
    msg: "{{ my_hostname }}"
